
version: '3.8'
name: Bank_REST

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bank-rest-app:
    image: tokarevv3/bank_rest:latest
    container_name: bank-rest-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password

      CUSTOM_JWT_SECRET: secret
      CUSTOM_JWT_EXPIRATION: 86400000
      CUSTOM_ENCRYPTION_ALGORITHM: AES
      CUSTOM_ENCRYPTION_SECRET: 1234567890123456

volumes:
  postgres-data:
