server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  liquibase:
    change-log: classpath:db/migration/001-create-tables-and-admin.yaml
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    enabled: true

logging:
  level:
    org.springframework.security: debug

custom:
  jwt:
    secret: ${CUSTOM_JWT_SECRET:secret}
    expiration: ${CUSTOM_JWT_EXPIRATION:86400000}
  encryption:
    algorithm: ${CUSTOM_ENCRYPTION_ALGORITHM:AES}
    secret: ${CUSTOM_ENCRYPTION_SECRET:1234567890123456}


