#
# application.yml — главный конфигурационный файл Spring Boot.
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

  liquibase:
    change-log: classpath:db/migration/001-create-tables-and-admin.yaml
    enabled: true

  security:
    allow-unauthenticated-paths:
      - /api/auth/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-resources/**
      - /webjars/**

jwt:
  secret: your-jwt-secret-key
  expiration: 3600000  # 1 час в миллисекундах
  issuer: your-app-name

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG


